# Mutagen Compose tests

version: '3.8'

networks:
  directus:

volumes:
  db_data:
  uploads:

services:
  db:
    container_name: database
    image: postgres:14-bullseye
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    ports:
      - 5432:5432
    networks:
      - directus
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:9
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      # - ./uploads:/directus/uploads
      - uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - db
    environment:
      KEY: 22C4D2F3-827F-4F38-9A4D-896216F8D775
      SECRET: 2FC2E36E-2782-4550-B96B-0815694E3ABA
      DB_CLIENT: pg
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: directus
      CACHE_ENABLED: true
      CACHE_STORE: redis
      CACHE_REDIS: redis://cache:6379
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: password
      # Make sure to set this in production
      # (see https://docs.directus.io/configuration/config-options/#general)
      # PUBLIC_URL: https://directus.example.com

